arr = list(map(int, input('Enter the array elements:- ').split()))
print(f'The array elements are:-\n{arr}')
print('Insertion in to array:-')
insert_arr = int(input('Enter an element to insert in to array:- '))
insert_to_arr = arr.append(insert_arr)
print(f'After insertion {insert_arr} in to array the array is:-\n{arr}')
print('Deletion from array:-')
delete_arr = int(input('Enter element to delete form array:-'))
delete_from_array = arr.remove(delete_arr)
print(f'After deletion {delete_arr} from the array the array is:-\n{arr}')
print('The length of the array:-')
print(f'The length of the array {arr} is:- {len(arr)}')